# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Abborn assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Abborn assignment
  
  pod 'RealmSwift'

  target 'Abborn assignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Abborn assignmentUITests' do
    # Pods for testing
  end

end
